var device = ["Keyboard","Mouse","Printer","Monitor"]
document.write("<b> Devices: </b>" +device)
document.write("<br>")
document.write("<br>")
var device1=device.pop(0)
document.write("<b> Out: </b> <br>" +device1)
document.write("<br>")
var device2=device.pop(1)
document.write("<b> Out: </b> <br>" +device2)
document.write("<br>")
var device3=device.pop(2)
document.write("<b> Out: </b> <br>" +device3)
document.write("<br>")
var device4=device.pop(3)
document.write("<b> Out: </b> <br>" +device4)

