var color = ["Black","White","Blue","Sky"]
document.write(" <b> COLORS LIST: </b>" +color)
document.write("<br>")
var addbeg = prompt("Which color you want to add in beginning?")
color.unshift(addbeg)
document.write("a)User add color from beginning is " +color )
document.write("<br>")
var addend = prompt("Which color you want to add in end of the array?")
color.push(addend)
document.write("b) User add color from last is " +color )
document.write("<br>")
var addbeg1 = prompt("Which color you want to add in beginning?")
var addbeg2 = prompt("Which color you want to add in beginning?")
color.splice(0,0,addbeg1,addbeg2)
document.write("c) Updated array after adding two more colors are " +color )
document.write("<br>")
color.shift()
document.write("d) First color deleted from the array " +color )
document.write("<br>")
color.pop()
document.write("e) Last color deleted from the array " +color )
document.write("<br>")
var position = prompt("At which index you want to add the color?")
var position1 = prompt("Name of color you want to add?")
color.splice(position,position1)
document.write("f) After adding color as user's wish " +color )
document.write("<br>")
var position2 = prompt("At which index you want to delete the color?")
var position3 = prompt("How many color you want to delete?")
color.splice(position2,position3)
document.write("g) After deleting color as user's wish " +color )
